<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>src</string>
	</array>
	<key>name</key>
	<string>Docular</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(@doc|@id|@name|@description)\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
	</array>
	<key>scope</key>
	<string>source.js</string>
	<key>scopeName</key>
	<string>source.untitled</string>
	<key>uuid</key>
	<string>73B963ED-AC9C-4DC6-93CD-389E1E4EBEFE</string>
</dict>
</plist>
